version: '3.7'
services:
    mongodb:
        # This image automatically creates a replica set required for transactions
        image: prismagraphql/mongo-single-replica:4.4.3-bionic
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongodb
            MONGO_INITDB_ROOT_PASSWORD: mongodb
            INIT_WAIT_SEC: 3
        ports:
            - 27017:27017
    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
